<?php

namespace App\Console\Commands;

use App\Models\Page;
use App\Models\Post;
use App\Models\Wallet;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

/**
 * Dumps every scrap of CMS-authored markup into one file so the Tailwind CLI
 * can scan it.
 *
 * Page bodies and Field Note bodies are raw HTML held in the database, not in
 * Blade files, so a `resources/views/**` glob alone would purge every utility
 * class that only ever appears in CMS content. The build runs this first and
 * points a content glob at the file it writes.
 *
 * All locales are dumped, not just the active one — the Ukrainian copy is a
 * separate translation row and can carry classes the English row does not.
 */
class TailwindContent extends Command
{
    protected $signature = 'tailwind:content {--path= : Write somewhere other than storage/app/tailwind/content.html}';

    protected $description = 'Dump all CMS-authored HTML into one file for Tailwind to scan';

    public function handle(): int
    {
        $path = $this->option('path') ?: storage_path('app/tailwind/content.html');

        File::ensureDirectoryExists(dirname($path));

        $chunks = [
            '<!-- Generated by `php artisan tailwind:content`. Do not edit; do not commit. -->',
        ];

        foreach (Page::all() as $page) {
            $chunks[] = $this->translations($page, ['title', 'eyebrow', 'lead', 'content', 'meta_title', 'meta_description']);
        }

        foreach (Post::all() as $post) {
            $chunks[] = $this->translations($post, ['title', 'excerpt', 'body', 'category']);
        }

        foreach (Wallet::all() as $wallet) {
            $chunks[] = $this->translations($wallet, ['name', 'network', 'address']);
        }

        $html = implode("\n", array_filter($chunks));

        File::put($path, $html);

        $this->info(sprintf('Wrote %s (%s KB).', $path, number_format(strlen($html) / 1024, 1)));

        return self::SUCCESS;
    }

    /**
     * Every locale of every named attribute on a model, flattened to one string.
     * Untranslatable (or absent) attributes fall back to the plain value, so
     * this is safe to point at any model.
     *
     * @param  array<int, string>  $attributes
     */
    protected function translations(mixed $model, array $attributes): string
    {
        $out = [];

        foreach ($attributes as $attribute) {
            if (! in_array($attribute, $model->getFillable(), true)) {
                continue;
            }

            $values = method_exists($model, 'getTranslations')
                ? $model->getTranslations($attribute)
                : [$model->getAttribute($attribute)];

            foreach ($values as $value) {
                if (is_string($value) && $value !== '') {
                    $out[] = $value;
                }
            }
        }

        return implode("\n", $out);
    }
}
